# Generated by Django 5.2.3 on 2025-07-02 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Место, где выполняется привычка",
                        max_length=200,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите время, когда необходимо выполнять привычку",
                        null=True,
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие, которое представляет собой привычка",
                        max_length=255,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Указывает, является ли привычка приятной",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "каждый день"),
                            (2, "через день"),
                            (3, "раз в 3 дня"),
                            (4, "раз в 4 дня"),
                            (5, "раз в 5 дней"),
                            (6, "раз в 6 дней"),
                            (7, "раз в неделю"),
                        ],
                        default=1,
                        help_text="Периодичность в днях (1-7)",
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Вознаграждение за выполнение привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "execution_time",
                    models.PositiveIntegerField(
                        help_text="Время выполнения в секундах (не более 120)", verbose_name="Время выполнения"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Доступна ли привычка для просмотра другими", verbose_name="Публичная"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Указывает, активна ли привычка", verbose_name="Активна"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Привычка-вознаграждение. Только приятные привычки",
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
