# Generated by Django 5.2.3 on 2025-07-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.PositiveIntegerField(
                choices=[
                    ("every day", "каждый день"),
                    ("every other day", "через день"),
                    ("every three days", "раз в 3 дня"),
                    ("every four days", "раз в 4 дня"),
                    ("every five days", "раз в 5 дней"),
                    ("every six days", "раз в 6 дней"),
                    ("every week", "раз в неделю"),
                ],
                default="every day",
                help_text="Периодичность в днях (1-7)",
                max_length=32,
                verbose_name="Периодичность выполнения",
            ),
        ),
    ]
