# Generated by Django 5.2.3 on 2025-07-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_period"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["-created_at"], "verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
    ]
